// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.31.0
// 	protoc        v3.12.4
// source: noolingo/cards.proto

package noolingo

import (
	common "github.com/MelnikovNA/noolingoproto/codegen/go/common"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CardObject struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id            string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Eng           string `protobuf:"bytes,2,opt,name=eng,proto3" json:"eng,omitempty"`
	Rus           string `protobuf:"bytes,3,opt,name=rus,proto3" json:"rus,omitempty"`
	Transcription string `protobuf:"bytes,4,opt,name=transcription,proto3" json:"transcription,omitempty"`
	Example       string `protobuf:"bytes,5,opt,name=example,proto3" json:"example,omitempty"`
}

func (x *CardObject) Reset() {
	*x = CardObject{}
	if protoimpl.UnsafeEnabled {
		mi := &file_noolingo_cards_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CardObject) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CardObject) ProtoMessage() {}

func (x *CardObject) ProtoReflect() protoreflect.Message {
	mi := &file_noolingo_cards_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CardObject.ProtoReflect.Descriptor instead.
func (*CardObject) Descriptor() ([]byte, []int) {
	return file_noolingo_cards_proto_rawDescGZIP(), []int{0}
}

func (x *CardObject) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *CardObject) GetEng() string {
	if x != nil {
		return x.Eng
	}
	return ""
}

func (x *CardObject) GetRus() string {
	if x != nil {
		return x.Rus
	}
	return ""
}

func (x *CardObject) GetTranscription() string {
	if x != nil {
		return x.Transcription
	}
	return ""
}

func (x *CardObject) GetExample() string {
	if x != nil {
		return x.Example
	}
	return ""
}

type SearchByIDRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id []string `protobuf:"bytes,1,rep,name=id,proto3" json:"id,omitempty"`
}

func (x *SearchByIDRequest) Reset() {
	*x = SearchByIDRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_noolingo_cards_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SearchByIDRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchByIDRequest) ProtoMessage() {}

func (x *SearchByIDRequest) ProtoReflect() protoreflect.Message {
	mi := &file_noolingo_cards_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchByIDRequest.ProtoReflect.Descriptor instead.
func (*SearchByIDRequest) Descriptor() ([]byte, []int) {
	return file_noolingo_cards_proto_rawDescGZIP(), []int{1}
}

func (x *SearchByIDRequest) GetId() []string {
	if x != nil {
		return x.Id
	}
	return nil
}

type SearchByEngRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Eng string `protobuf:"bytes,1,opt,name=eng,proto3" json:"eng,omitempty"`
}

func (x *SearchByEngRequest) Reset() {
	*x = SearchByEngRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_noolingo_cards_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SearchByEngRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchByEngRequest) ProtoMessage() {}

func (x *SearchByEngRequest) ProtoReflect() protoreflect.Message {
	mi := &file_noolingo_cards_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchByEngRequest.ProtoReflect.Descriptor instead.
func (*SearchByEngRequest) Descriptor() ([]byte, []int) {
	return file_noolingo_cards_proto_rawDescGZIP(), []int{2}
}

func (x *SearchByEngRequest) GetEng() string {
	if x != nil {
		return x.Eng
	}
	return ""
}

type SearchByRusRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Rus string `protobuf:"bytes,1,opt,name=rus,proto3" json:"rus,omitempty"`
}

func (x *SearchByRusRequest) Reset() {
	*x = SearchByRusRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_noolingo_cards_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SearchByRusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchByRusRequest) ProtoMessage() {}

func (x *SearchByRusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_noolingo_cards_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchByRusRequest.ProtoReflect.Descriptor instead.
func (*SearchByRusRequest) Descriptor() ([]byte, []int) {
	return file_noolingo_cards_proto_rawDescGZIP(), []int{3}
}

func (x *SearchByRusRequest) GetRus() string {
	if x != nil {
		return x.Rus
	}
	return ""
}

type SearchReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Cards    []*CardObject    `protobuf:"bytes,1,rep,name=cards,proto3" json:"cards,omitempty"`
	Response *common.Response `protobuf:"bytes,2,opt,name=response,proto3" json:"response,omitempty"`
}

func (x *SearchReply) Reset() {
	*x = SearchReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_noolingo_cards_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SearchReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchReply) ProtoMessage() {}

func (x *SearchReply) ProtoReflect() protoreflect.Message {
	mi := &file_noolingo_cards_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchReply.ProtoReflect.Descriptor instead.
func (*SearchReply) Descriptor() ([]byte, []int) {
	return file_noolingo_cards_proto_rawDescGZIP(), []int{4}
}

func (x *SearchReply) GetCards() []*CardObject {
	if x != nil {
		return x.Cards
	}
	return nil
}

func (x *SearchReply) GetResponse() *common.Response {
	if x != nil {
		return x.Response
	}
	return nil
}

var File_noolingo_cards_proto protoreflect.FileDescriptor

var file_noolingo_cards_proto_rawDesc = []byte{
	0x0a, 0x14, 0x6e, 0x6f, 0x6f, 0x6c, 0x69, 0x6e, 0x67, 0x6f, 0x2f, 0x63, 0x61, 0x72, 0x64, 0x73,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x08, 0x6e, 0x6f, 0x6f, 0x6c, 0x69, 0x6e, 0x67, 0x6f,
	0x1a, 0x1c, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x61, 0x6e, 0x6e,
	0x6f, 0x74, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x13,
	0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2f, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x22, 0x80, 0x01, 0x0a, 0x0a, 0x43, 0x61, 0x72, 0x64, 0x4f, 0x62, 0x6a, 0x65,
	0x63, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02,
	0x69, 0x64, 0x12, 0x10, 0x0a, 0x03, 0x65, 0x6e, 0x67, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x03, 0x65, 0x6e, 0x67, 0x12, 0x10, 0x0a, 0x03, 0x72, 0x75, 0x73, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x03, 0x72, 0x75, 0x73, 0x12, 0x24, 0x0a, 0x0d, 0x74, 0x72, 0x61, 0x6e, 0x73, 0x63,
	0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0d, 0x74,
	0x72, 0x61, 0x6e, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x18, 0x0a, 0x07,
	0x65, 0x78, 0x61, 0x6d, 0x70, 0x6c, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x65,
	0x78, 0x61, 0x6d, 0x70, 0x6c, 0x65, 0x22, 0x23, 0x0a, 0x11, 0x53, 0x65, 0x61, 0x72, 0x63, 0x68,
	0x42, 0x79, 0x49, 0x44, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69,
	0x64, 0x18, 0x01, 0x20, 0x03, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x22, 0x26, 0x0a, 0x12, 0x53,
	0x65, 0x61, 0x72, 0x63, 0x68, 0x42, 0x79, 0x45, 0x6e, 0x67, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x12, 0x10, 0x0a, 0x03, 0x65, 0x6e, 0x67, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03,
	0x65, 0x6e, 0x67, 0x22, 0x26, 0x0a, 0x12, 0x53, 0x65, 0x61, 0x72, 0x63, 0x68, 0x42, 0x79, 0x52,
	0x75, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x10, 0x0a, 0x03, 0x72, 0x75, 0x73,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x72, 0x75, 0x73, 0x22, 0x67, 0x0a, 0x0b, 0x53,
	0x65, 0x61, 0x72, 0x63, 0x68, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x2a, 0x0a, 0x05, 0x63, 0x61,
	0x72, 0x64, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x14, 0x2e, 0x6e, 0x6f, 0x6f, 0x6c,
	0x69, 0x6e, 0x67, 0x6f, 0x2e, 0x43, 0x61, 0x72, 0x64, 0x4f, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x52,
	0x05, 0x63, 0x61, 0x72, 0x64, 0x73, 0x12, 0x2c, 0x0a, 0x08, 0x72, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x10, 0x2e, 0x63, 0x6f, 0x6d, 0x6d, 0x6f,
	0x6e, 0x2e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x52, 0x08, 0x72, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x32, 0xa1, 0x02, 0x0a, 0x05, 0x43, 0x61, 0x72, 0x64, 0x73, 0x12, 0x5a,
	0x0a, 0x0a, 0x53, 0x65, 0x61, 0x72, 0x63, 0x68, 0x42, 0x79, 0x49, 0x44, 0x12, 0x1b, 0x2e, 0x6e,
	0x6f, 0x6f, 0x6c, 0x69, 0x6e, 0x67, 0x6f, 0x2e, 0x53, 0x65, 0x61, 0x72, 0x63, 0x68, 0x42, 0x79,
	0x49, 0x44, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x15, 0x2e, 0x6e, 0x6f, 0x6f, 0x6c,
	0x69, 0x6e, 0x67, 0x6f, 0x2e, 0x53, 0x65, 0x61, 0x72, 0x63, 0x68, 0x52, 0x65, 0x70, 0x6c, 0x79,
	0x22, 0x18, 0x82, 0xd3, 0xe4, 0x93, 0x02, 0x12, 0x12, 0x10, 0x2f, 0x63, 0x61, 0x72, 0x64, 0x2f,
	0x77, 0x6f, 0x72, 0x64, 0x73, 0x2f, 0x7b, 0x69, 0x64, 0x7d, 0x12, 0x5d, 0x0a, 0x0b, 0x53, 0x65,
	0x61, 0x72, 0x63, 0x68, 0x42, 0x79, 0x52, 0x75, 0x73, 0x12, 0x1c, 0x2e, 0x6e, 0x6f, 0x6f, 0x6c,
	0x69, 0x6e, 0x67, 0x6f, 0x2e, 0x53, 0x65, 0x61, 0x72, 0x63, 0x68, 0x42, 0x79, 0x52, 0x75, 0x73,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x15, 0x2e, 0x6e, 0x6f, 0x6f, 0x6c, 0x69, 0x6e,
	0x67, 0x6f, 0x2e, 0x53, 0x65, 0x61, 0x72, 0x63, 0x68, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x22, 0x19,
	0x82, 0xd3, 0xe4, 0x93, 0x02, 0x13, 0x12, 0x11, 0x2f, 0x63, 0x61, 0x72, 0x64, 0x2f, 0x77, 0x6f,
	0x72, 0x64, 0x73, 0x2f, 0x7b, 0x72, 0x75, 0x73, 0x7d, 0x12, 0x5d, 0x0a, 0x0b, 0x53, 0x65, 0x61,
	0x72, 0x63, 0x68, 0x42, 0x79, 0x45, 0x6e, 0x67, 0x12, 0x1c, 0x2e, 0x6e, 0x6f, 0x6f, 0x6c, 0x69,
	0x6e, 0x67, 0x6f, 0x2e, 0x53, 0x65, 0x61, 0x72, 0x63, 0x68, 0x42, 0x79, 0x45, 0x6e, 0x67, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x15, 0x2e, 0x6e, 0x6f, 0x6f, 0x6c, 0x69, 0x6e, 0x67,
	0x6f, 0x2e, 0x53, 0x65, 0x61, 0x72, 0x63, 0x68, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x22, 0x19, 0x82,
	0xd3, 0xe4, 0x93, 0x02, 0x13, 0x12, 0x11, 0x2f, 0x63, 0x61, 0x72, 0x64, 0x2f, 0x77, 0x6f, 0x72,
	0x64, 0x73, 0x2f, 0x7b, 0x65, 0x6e, 0x67, 0x7d, 0x42, 0x39, 0x5a, 0x37, 0x67, 0x69, 0x74, 0x68,
	0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x4d, 0x65, 0x6c, 0x6e, 0x69, 0x6b, 0x6f, 0x76, 0x4e,
	0x41, 0x2f, 0x6e, 0x6f, 0x6f, 0x6c, 0x69, 0x6e, 0x67, 0x6f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f,
	0x63, 0x6f, 0x64, 0x65, 0x67, 0x65, 0x6e, 0x2f, 0x67, 0x6f, 0x2f, 0x6e, 0x6f, 0x6f, 0x6c, 0x69,
	0x6e, 0x67, 0x6f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_noolingo_cards_proto_rawDescOnce sync.Once
	file_noolingo_cards_proto_rawDescData = file_noolingo_cards_proto_rawDesc
)

func file_noolingo_cards_proto_rawDescGZIP() []byte {
	file_noolingo_cards_proto_rawDescOnce.Do(func() {
		file_noolingo_cards_proto_rawDescData = protoimpl.X.CompressGZIP(file_noolingo_cards_proto_rawDescData)
	})
	return file_noolingo_cards_proto_rawDescData
}

var file_noolingo_cards_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_noolingo_cards_proto_goTypes = []interface{}{
	(*CardObject)(nil),         // 0: noolingo.CardObject
	(*SearchByIDRequest)(nil),  // 1: noolingo.SearchByIDRequest
	(*SearchByEngRequest)(nil), // 2: noolingo.SearchByEngRequest
	(*SearchByRusRequest)(nil), // 3: noolingo.SearchByRusRequest
	(*SearchReply)(nil),        // 4: noolingo.SearchReply
	(*common.Response)(nil),    // 5: common.Response
}
var file_noolingo_cards_proto_depIdxs = []int32{
	0, // 0: noolingo.SearchReply.cards:type_name -> noolingo.CardObject
	5, // 1: noolingo.SearchReply.response:type_name -> common.Response
	1, // 2: noolingo.Cards.SearchByID:input_type -> noolingo.SearchByIDRequest
	3, // 3: noolingo.Cards.SearchByRus:input_type -> noolingo.SearchByRusRequest
	2, // 4: noolingo.Cards.SearchByEng:input_type -> noolingo.SearchByEngRequest
	4, // 5: noolingo.Cards.SearchByID:output_type -> noolingo.SearchReply
	4, // 6: noolingo.Cards.SearchByRus:output_type -> noolingo.SearchReply
	4, // 7: noolingo.Cards.SearchByEng:output_type -> noolingo.SearchReply
	5, // [5:8] is the sub-list for method output_type
	2, // [2:5] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_noolingo_cards_proto_init() }
func file_noolingo_cards_proto_init() {
	if File_noolingo_cards_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_noolingo_cards_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CardObject); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_noolingo_cards_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SearchByIDRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_noolingo_cards_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SearchByEngRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_noolingo_cards_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SearchByRusRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_noolingo_cards_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SearchReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_noolingo_cards_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_noolingo_cards_proto_goTypes,
		DependencyIndexes: file_noolingo_cards_proto_depIdxs,
		MessageInfos:      file_noolingo_cards_proto_msgTypes,
	}.Build()
	File_noolingo_cards_proto = out.File
	file_noolingo_cards_proto_rawDesc = nil
	file_noolingo_cards_proto_goTypes = nil
	file_noolingo_cards_proto_depIdxs = nil
}
