// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.31.0
// 	protoc        v3.21.12
// source: noolingo/deck.proto

package noolingo

import (
	common "github.com/noolingo/proto/codegen/go/common"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type DeckObject struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id      string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	CardIds []string `protobuf:"bytes,2,rep,name=card_ids,json=cardIds,proto3" json:"card_ids,omitempty"`
	Name    string   `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
}

func (x *DeckObject) Reset() {
	*x = DeckObject{}
	if protoimpl.UnsafeEnabled {
		mi := &file_noolingo_deck_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeckObject) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeckObject) ProtoMessage() {}

func (x *DeckObject) ProtoReflect() protoreflect.Message {
	mi := &file_noolingo_deck_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeckObject.ProtoReflect.Descriptor instead.
func (*DeckObject) Descriptor() ([]byte, []int) {
	return file_noolingo_deck_proto_rawDescGZIP(), []int{0}
}

func (x *DeckObject) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *DeckObject) GetCardIds() []string {
	if x != nil {
		return x.CardIds
	}
	return nil
}

func (x *DeckObject) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type DeckCreateRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name        string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Description string `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
}

func (x *DeckCreateRequest) Reset() {
	*x = DeckCreateRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_noolingo_deck_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeckCreateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeckCreateRequest) ProtoMessage() {}

func (x *DeckCreateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_noolingo_deck_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeckCreateRequest.ProtoReflect.Descriptor instead.
func (*DeckCreateRequest) Descriptor() ([]byte, []int) {
	return file_noolingo_deck_proto_rawDescGZIP(), []int{1}
}

func (x *DeckCreateRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *DeckCreateRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

type CardAddRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	DeckId string `protobuf:"bytes,1,opt,name=deck_id,json=deckId,proto3" json:"deck_id,omitempty"`
	CardId string `protobuf:"bytes,2,opt,name=card_id,json=cardId,proto3" json:"card_id,omitempty"`
}

func (x *CardAddRequest) Reset() {
	*x = CardAddRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_noolingo_deck_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CardAddRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CardAddRequest) ProtoMessage() {}

func (x *CardAddRequest) ProtoReflect() protoreflect.Message {
	mi := &file_noolingo_deck_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CardAddRequest.ProtoReflect.Descriptor instead.
func (*CardAddRequest) Descriptor() ([]byte, []int) {
	return file_noolingo_deck_proto_rawDescGZIP(), []int{2}
}

func (x *CardAddRequest) GetDeckId() string {
	if x != nil {
		return x.DeckId
	}
	return ""
}

func (x *CardAddRequest) GetCardId() string {
	if x != nil {
		return x.CardId
	}
	return ""
}

type CardDeleteRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	DeckId string `protobuf:"bytes,1,opt,name=deck_id,json=deckId,proto3" json:"deck_id,omitempty"`
	CardId string `protobuf:"bytes,2,opt,name=card_id,json=cardId,proto3" json:"card_id,omitempty"`
}

func (x *CardDeleteRequest) Reset() {
	*x = CardDeleteRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_noolingo_deck_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CardDeleteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CardDeleteRequest) ProtoMessage() {}

func (x *CardDeleteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_noolingo_deck_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CardDeleteRequest.ProtoReflect.Descriptor instead.
func (*CardDeleteRequest) Descriptor() ([]byte, []int) {
	return file_noolingo_deck_proto_rawDescGZIP(), []int{3}
}

func (x *CardDeleteRequest) GetDeckId() string {
	if x != nil {
		return x.DeckId
	}
	return ""
}

func (x *CardDeleteRequest) GetCardId() string {
	if x != nil {
		return x.CardId
	}
	return ""
}

type DeckDeleteRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	DeckId string `protobuf:"bytes,1,opt,name=deck_id,json=deckId,proto3" json:"deck_id,omitempty"`
}

func (x *DeckDeleteRequest) Reset() {
	*x = DeckDeleteRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_noolingo_deck_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeckDeleteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeckDeleteRequest) ProtoMessage() {}

func (x *DeckDeleteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_noolingo_deck_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeckDeleteRequest.ProtoReflect.Descriptor instead.
func (*DeckDeleteRequest) Descriptor() ([]byte, []int) {
	return file_noolingo_deck_proto_rawDescGZIP(), []int{4}
}

func (x *DeckDeleteRequest) GetDeckId() string {
	if x != nil {
		return x.DeckId
	}
	return ""
}

type DeckListRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *DeckListRequest) Reset() {
	*x = DeckListRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_noolingo_deck_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeckListRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeckListRequest) ProtoMessage() {}

func (x *DeckListRequest) ProtoReflect() protoreflect.Message {
	mi := &file_noolingo_deck_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeckListRequest.ProtoReflect.Descriptor instead.
func (*DeckListRequest) Descriptor() ([]byte, []int) {
	return file_noolingo_deck_proto_rawDescGZIP(), []int{5}
}

func (x *DeckListRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type DeckCreateResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	DeckID   string        `protobuf:"bytes,1,opt,name=deckID,proto3" json:"deckID,omitempty"`
	Response *common.Error `protobuf:"bytes,2,opt,name=response,proto3,oneof" json:"response,omitempty"`
}

func (x *DeckCreateResponse) Reset() {
	*x = DeckCreateResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_noolingo_deck_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeckCreateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeckCreateResponse) ProtoMessage() {}

func (x *DeckCreateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_noolingo_deck_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeckCreateResponse.ProtoReflect.Descriptor instead.
func (*DeckCreateResponse) Descriptor() ([]byte, []int) {
	return file_noolingo_deck_proto_rawDescGZIP(), []int{6}
}

func (x *DeckCreateResponse) GetDeckID() string {
	if x != nil {
		return x.DeckID
	}
	return ""
}

func (x *DeckCreateResponse) GetResponse() *common.Error {
	if x != nil {
		return x.Response
	}
	return nil
}

type CardAddResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	DeckId   string        `protobuf:"bytes,1,opt,name=deck_id,json=deckId,proto3" json:"deck_id,omitempty"`
	CardId   string        `protobuf:"bytes,2,opt,name=card_id,json=cardId,proto3" json:"card_id,omitempty"`
	Response *common.Error `protobuf:"bytes,3,opt,name=response,proto3,oneof" json:"response,omitempty"`
}

func (x *CardAddResponse) Reset() {
	*x = CardAddResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_noolingo_deck_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CardAddResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CardAddResponse) ProtoMessage() {}

func (x *CardAddResponse) ProtoReflect() protoreflect.Message {
	mi := &file_noolingo_deck_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CardAddResponse.ProtoReflect.Descriptor instead.
func (*CardAddResponse) Descriptor() ([]byte, []int) {
	return file_noolingo_deck_proto_rawDescGZIP(), []int{7}
}

func (x *CardAddResponse) GetDeckId() string {
	if x != nil {
		return x.DeckId
	}
	return ""
}

func (x *CardAddResponse) GetCardId() string {
	if x != nil {
		return x.CardId
	}
	return ""
}

func (x *CardAddResponse) GetResponse() *common.Error {
	if x != nil {
		return x.Response
	}
	return nil
}

type DeckListResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	DeckIDs  *DeckObject   `protobuf:"bytes,1,opt,name=deckIDs,proto3" json:"deckIDs,omitempty"`
	Response *common.Error `protobuf:"bytes,2,opt,name=response,proto3,oneof" json:"response,omitempty"`
}

func (x *DeckListResponse) Reset() {
	*x = DeckListResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_noolingo_deck_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeckListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeckListResponse) ProtoMessage() {}

func (x *DeckListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_noolingo_deck_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeckListResponse.ProtoReflect.Descriptor instead.
func (*DeckListResponse) Descriptor() ([]byte, []int) {
	return file_noolingo_deck_proto_rawDescGZIP(), []int{8}
}

func (x *DeckListResponse) GetDeckIDs() *DeckObject {
	if x != nil {
		return x.DeckIDs
	}
	return nil
}

func (x *DeckListResponse) GetResponse() *common.Error {
	if x != nil {
		return x.Response
	}
	return nil
}

var File_noolingo_deck_proto protoreflect.FileDescriptor

var file_noolingo_deck_proto_rawDesc = []byte{
	0x0a, 0x13, 0x6e, 0x6f, 0x6f, 0x6c, 0x69, 0x6e, 0x67, 0x6f, 0x2f, 0x64, 0x65, 0x63, 0x6b, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x08, 0x6e, 0x6f, 0x6f, 0x6c, 0x69, 0x6e, 0x67, 0x6f, 0x1a,
	0x1c, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x61, 0x6e, 0x6e, 0x6f,
	0x74, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x13, 0x63,
	0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2f, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x22, 0x4b, 0x0a, 0x0a, 0x44, 0x65, 0x63, 0x6b, 0x4f, 0x62, 0x6a, 0x65, 0x63, 0x74,
	0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64,
	0x12, 0x19, 0x0a, 0x08, 0x63, 0x61, 0x72, 0x64, 0x5f, 0x69, 0x64, 0x73, 0x18, 0x02, 0x20, 0x03,
	0x28, 0x09, 0x52, 0x07, 0x63, 0x61, 0x72, 0x64, 0x49, 0x64, 0x73, 0x12, 0x12, 0x0a, 0x04, 0x6e,
	0x61, 0x6d, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x22,
	0x49, 0x0a, 0x11, 0x44, 0x65, 0x63, 0x6b, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x20, 0x0a, 0x0b, 0x64, 0x65, 0x73, 0x63,
	0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x64,
	0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x22, 0x42, 0x0a, 0x0e, 0x43, 0x61,
	0x72, 0x64, 0x41, 0x64, 0x64, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x17, 0x0a, 0x07,
	0x64, 0x65, 0x63, 0x6b, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x64,
	0x65, 0x63, 0x6b, 0x49, 0x64, 0x12, 0x17, 0x0a, 0x07, 0x63, 0x61, 0x72, 0x64, 0x5f, 0x69, 0x64,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x63, 0x61, 0x72, 0x64, 0x49, 0x64, 0x22, 0x45,
	0x0a, 0x11, 0x43, 0x61, 0x72, 0x64, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x12, 0x17, 0x0a, 0x07, 0x64, 0x65, 0x63, 0x6b, 0x5f, 0x69, 0x64, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x64, 0x65, 0x63, 0x6b, 0x49, 0x64, 0x12, 0x17, 0x0a, 0x07,
	0x63, 0x61, 0x72, 0x64, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x63,
	0x61, 0x72, 0x64, 0x49, 0x64, 0x22, 0x2c, 0x0a, 0x11, 0x44, 0x65, 0x63, 0x6b, 0x44, 0x65, 0x6c,
	0x65, 0x74, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x17, 0x0a, 0x07, 0x64, 0x65,
	0x63, 0x6b, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x64, 0x65, 0x63,
	0x6b, 0x49, 0x64, 0x22, 0x21, 0x0a, 0x0f, 0x44, 0x65, 0x63, 0x6b, 0x4c, 0x69, 0x73, 0x74, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x22, 0x69, 0x0a, 0x12, 0x44, 0x65, 0x63, 0x6b, 0x43, 0x72,
	0x65, 0x61, 0x74, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x16, 0x0a, 0x06,
	0x64, 0x65, 0x63, 0x6b, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x64, 0x65,
	0x63, 0x6b, 0x49, 0x44, 0x12, 0x2e, 0x0a, 0x08, 0x72, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0d, 0x2e, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2e,
	0x45, 0x72, 0x72, 0x6f, 0x72, 0x48, 0x00, 0x52, 0x08, 0x72, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x88, 0x01, 0x01, 0x42, 0x0b, 0x0a, 0x09, 0x5f, 0x72, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x22, 0x80, 0x01, 0x0a, 0x0f, 0x43, 0x61, 0x72, 0x64, 0x41, 0x64, 0x64, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x17, 0x0a, 0x07, 0x64, 0x65, 0x63, 0x6b, 0x5f, 0x69, 0x64,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x64, 0x65, 0x63, 0x6b, 0x49, 0x64, 0x12, 0x17,
	0x0a, 0x07, 0x63, 0x61, 0x72, 0x64, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x06, 0x63, 0x61, 0x72, 0x64, 0x49, 0x64, 0x12, 0x2e, 0x0a, 0x08, 0x72, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0d, 0x2e, 0x63, 0x6f, 0x6d, 0x6d,
	0x6f, 0x6e, 0x2e, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x48, 0x00, 0x52, 0x08, 0x72, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x88, 0x01, 0x01, 0x42, 0x0b, 0x0a, 0x09, 0x5f, 0x72, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x22, 0x7f, 0x0a, 0x10, 0x44, 0x65, 0x63, 0x6b, 0x4c, 0x69, 0x73, 0x74,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x2e, 0x0a, 0x07, 0x64, 0x65, 0x63, 0x6b,
	0x49, 0x44, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x14, 0x2e, 0x6e, 0x6f, 0x6f, 0x6c,
	0x69, 0x6e, 0x67, 0x6f, 0x2e, 0x44, 0x65, 0x63, 0x6b, 0x4f, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x52,
	0x07, 0x64, 0x65, 0x63, 0x6b, 0x49, 0x44, 0x73, 0x12, 0x2e, 0x0a, 0x08, 0x72, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0d, 0x2e, 0x63, 0x6f, 0x6d,
	0x6d, 0x6f, 0x6e, 0x2e, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x48, 0x00, 0x52, 0x08, 0x72, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x88, 0x01, 0x01, 0x42, 0x0b, 0x0a, 0x09, 0x5f, 0x72, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x32, 0xc7, 0x03, 0x0a, 0x04, 0x44, 0x65, 0x63, 0x6b, 0x12, 0x5a,
	0x0a, 0x0a, 0x44, 0x65, 0x63, 0x6b, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x12, 0x1b, 0x2e, 0x6e,
	0x6f, 0x6f, 0x6c, 0x69, 0x6e, 0x67, 0x6f, 0x2e, 0x44, 0x65, 0x63, 0x6b, 0x43, 0x72, 0x65, 0x61,
	0x74, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1c, 0x2e, 0x6e, 0x6f, 0x6f, 0x6c,
	0x69, 0x6e, 0x67, 0x6f, 0x2e, 0x44, 0x65, 0x63, 0x6b, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x11, 0x82, 0xd3, 0xe4, 0x93, 0x02, 0x0b, 0x3a,
	0x01, 0x2a, 0x22, 0x06, 0x2f, 0x64, 0x65, 0x63, 0x6b, 0x73, 0x12, 0x57, 0x0a, 0x07, 0x43, 0x61,
	0x72, 0x64, 0x41, 0x64, 0x64, 0x12, 0x18, 0x2e, 0x6e, 0x6f, 0x6f, 0x6c, 0x69, 0x6e, 0x67, 0x6f,
	0x2e, 0x43, 0x61, 0x72, 0x64, 0x41, 0x64, 0x64, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a,
	0x19, 0x2e, 0x6e, 0x6f, 0x6f, 0x6c, 0x69, 0x6e, 0x67, 0x6f, 0x2e, 0x43, 0x61, 0x72, 0x64, 0x41,
	0x64, 0x64, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x17, 0x82, 0xd3, 0xe4, 0x93,
	0x02, 0x11, 0x3a, 0x01, 0x2a, 0x1a, 0x0c, 0x2f, 0x64, 0x65, 0x63, 0x6b, 0x73, 0x2f, 0x63, 0x61,
	0x72, 0x64, 0x73, 0x12, 0x65, 0x0a, 0x0a, 0x43, 0x61, 0x72, 0x64, 0x44, 0x65, 0x6c, 0x65, 0x74,
	0x65, 0x12, 0x1b, 0x2e, 0x6e, 0x6f, 0x6f, 0x6c, 0x69, 0x6e, 0x67, 0x6f, 0x2e, 0x43, 0x61, 0x72,
	0x64, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x10,
	0x2e, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x22, 0x28, 0x82, 0xd3, 0xe4, 0x93, 0x02, 0x22, 0x2a, 0x20, 0x2f, 0x64, 0x65, 0x63, 0x6b, 0x73,
	0x2f, 0x7b, 0x64, 0x65, 0x63, 0x6b, 0x5f, 0x69, 0x64, 0x7d, 0x2f, 0x63, 0x61, 0x72, 0x64, 0x73,
	0x2f, 0x7b, 0x63, 0x61, 0x72, 0x64, 0x5f, 0x69, 0x64, 0x7d, 0x12, 0x55, 0x0a, 0x0a, 0x44, 0x65,
	0x63, 0x6b, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x12, 0x1b, 0x2e, 0x6e, 0x6f, 0x6f, 0x6c, 0x69,
	0x6e, 0x67, 0x6f, 0x2e, 0x44, 0x65, 0x63, 0x6b, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x10, 0x2e, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2e, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x18, 0x82, 0xd3, 0xe4, 0x93, 0x02, 0x12, 0x2a,
	0x10, 0x2f, 0x64, 0x65, 0x63, 0x6b, 0x73, 0x2f, 0x7b, 0x64, 0x65, 0x63, 0x6b, 0x5f, 0x69, 0x64,
	0x7d, 0x12, 0x4c, 0x0a, 0x08, 0x44, 0x65, 0x63, 0x6b, 0x4c, 0x69, 0x73, 0x74, 0x12, 0x19, 0x2e,
	0x6e, 0x6f, 0x6f, 0x6c, 0x69, 0x6e, 0x67, 0x6f, 0x2e, 0x44, 0x65, 0x63, 0x6b, 0x4c, 0x69, 0x73,
	0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x10, 0x2e, 0x63, 0x6f, 0x6d, 0x6d, 0x6f,
	0x6e, 0x2e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x13, 0x82, 0xd3, 0xe4, 0x93,
	0x02, 0x0d, 0x12, 0x0b, 0x2f, 0x64, 0x65, 0x63, 0x6b, 0x73, 0x2f, 0x7b, 0x69, 0x64, 0x7d, 0x42,
	0x2f, 0x5a, 0x2d, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x6e, 0x6f,
	0x6f, 0x6c, 0x69, 0x6e, 0x67, 0x6f, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x63, 0x6f, 0x64,
	0x65, 0x67, 0x65, 0x6e, 0x2f, 0x67, 0x6f, 0x2f, 0x6e, 0x6f, 0x6f, 0x6c, 0x69, 0x6e, 0x67, 0x6f,
	0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_noolingo_deck_proto_rawDescOnce sync.Once
	file_noolingo_deck_proto_rawDescData = file_noolingo_deck_proto_rawDesc
)

func file_noolingo_deck_proto_rawDescGZIP() []byte {
	file_noolingo_deck_proto_rawDescOnce.Do(func() {
		file_noolingo_deck_proto_rawDescData = protoimpl.X.CompressGZIP(file_noolingo_deck_proto_rawDescData)
	})
	return file_noolingo_deck_proto_rawDescData
}

var file_noolingo_deck_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_noolingo_deck_proto_goTypes = []interface{}{
	(*DeckObject)(nil),         // 0: noolingo.DeckObject
	(*DeckCreateRequest)(nil),  // 1: noolingo.DeckCreateRequest
	(*CardAddRequest)(nil),     // 2: noolingo.CardAddRequest
	(*CardDeleteRequest)(nil),  // 3: noolingo.CardDeleteRequest
	(*DeckDeleteRequest)(nil),  // 4: noolingo.DeckDeleteRequest
	(*DeckListRequest)(nil),    // 5: noolingo.DeckListRequest
	(*DeckCreateResponse)(nil), // 6: noolingo.DeckCreateResponse
	(*CardAddResponse)(nil),    // 7: noolingo.CardAddResponse
	(*DeckListResponse)(nil),   // 8: noolingo.DeckListResponse
	(*common.Error)(nil),       // 9: common.Error
	(*common.Response)(nil),    // 10: common.Response
}
var file_noolingo_deck_proto_depIdxs = []int32{
	9,  // 0: noolingo.DeckCreateResponse.response:type_name -> common.Error
	9,  // 1: noolingo.CardAddResponse.response:type_name -> common.Error
	0,  // 2: noolingo.DeckListResponse.deckIDs:type_name -> noolingo.DeckObject
	9,  // 3: noolingo.DeckListResponse.response:type_name -> common.Error
	1,  // 4: noolingo.Deck.DeckCreate:input_type -> noolingo.DeckCreateRequest
	2,  // 5: noolingo.Deck.CardAdd:input_type -> noolingo.CardAddRequest
	3,  // 6: noolingo.Deck.CardDelete:input_type -> noolingo.CardDeleteRequest
	4,  // 7: noolingo.Deck.DeckDelete:input_type -> noolingo.DeckDeleteRequest
	5,  // 8: noolingo.Deck.DeckList:input_type -> noolingo.DeckListRequest
	6,  // 9: noolingo.Deck.DeckCreate:output_type -> noolingo.DeckCreateResponse
	7,  // 10: noolingo.Deck.CardAdd:output_type -> noolingo.CardAddResponse
	10, // 11: noolingo.Deck.CardDelete:output_type -> common.Response
	10, // 12: noolingo.Deck.DeckDelete:output_type -> common.Response
	10, // 13: noolingo.Deck.DeckList:output_type -> common.Response
	9,  // [9:14] is the sub-list for method output_type
	4,  // [4:9] is the sub-list for method input_type
	4,  // [4:4] is the sub-list for extension type_name
	4,  // [4:4] is the sub-list for extension extendee
	0,  // [0:4] is the sub-list for field type_name
}

func init() { file_noolingo_deck_proto_init() }
func file_noolingo_deck_proto_init() {
	if File_noolingo_deck_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_noolingo_deck_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeckObject); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_noolingo_deck_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeckCreateRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_noolingo_deck_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CardAddRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_noolingo_deck_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CardDeleteRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_noolingo_deck_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeckDeleteRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_noolingo_deck_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeckListRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_noolingo_deck_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeckCreateResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_noolingo_deck_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CardAddResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_noolingo_deck_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeckListResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_noolingo_deck_proto_msgTypes[6].OneofWrappers = []interface{}{}
	file_noolingo_deck_proto_msgTypes[7].OneofWrappers = []interface{}{}
	file_noolingo_deck_proto_msgTypes[8].OneofWrappers = []interface{}{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_noolingo_deck_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_noolingo_deck_proto_goTypes,
		DependencyIndexes: file_noolingo_deck_proto_depIdxs,
		MessageInfos:      file_noolingo_deck_proto_msgTypes,
	}.Build()
	File_noolingo_deck_proto = out.File
	file_noolingo_deck_proto_rawDesc = nil
	file_noolingo_deck_proto_goTypes = nil
	file_noolingo_deck_proto_depIdxs = nil
}
